course:
  course_id: 287410
  score:
    choice: 1
    matching: 2
    code: 5
    sorting: 1
    number: 3
    string: 3
    text: null

sections:
  - title: Пора знакомиться
    lessons:
      - title: Начало
        steps: biotech-lection/0_intro/10_intro.yaml
      - title: О физике, как надо
        steps: biotech-lection/0_intro/21_about.md
      - title: О моделях и экспериментах
        steps: biotech-lection/0_intro/30_experience.yaml
  - title: Механика
    lessons:
      - title: Кинематика
        steps: biotech-lection/1_mech/10_kinematic.yaml
      - title: Динамика
        steps: biotech-lection/1_mech/20_dynamics.yaml
      - title: Работа и энергия
        steps: biotech-lection/1_mech/30_energy.yaml
      - title: Колебательное движение точки
        steps: biotech-lection/1_mech/40_oscillation.yaml
      - title: Движение по окружности
        steps: biotech-lection/1_mech/50_circle.yaml
      - title: Волны
        steps: biotech-lection/1_mech/60_wave.yaml
  - title: МКТ и термодинамика
    lessons:
      - title: Явления переноса
        steps: biotech-lection/2_mkt/10_phenomen_transfer.yaml
      - title: МКТ (начало)
        steps: biotech-lection/2_mkt/20_mkt.yaml
      - title: МКТ (ещё раз)
        steps: biotech-lection/2_mkt/30_mkt.yaml
      - title: Термодинамика
        steps: biotech-lection/2_mkt/40_tds.yaml
      - title: Термодинамические процессы
        steps: biotech-lection/2_mkt/50_tds.yaml
      - title: Термодинамика (второй закон и энтропия)
        steps: biotech-lection/2_mkt/60_tds.yaml
  - title: Электромагнитные явления
    lessons:
      - title: Электростатика
        steps: biotech-lection/3_em/10_electro.yaml
      - title: Потенциал электрического поля
        steps: biotech-lection/3_em/20_electro.yaml
      - title: Электроёмкость
        steps: biotech-lection/3_em/30_electro.yaml
      - title: Законы постоянного тока
        steps: biotech-lection/3_em/40_electric.yaml
      - title: Продолжаем изучать постоянный ток
        steps: biotech-lection/3_em/50_electric.yaml
      - title: Магнетизм
        steps: biotech-lection/3_em/60_magnetic.yaml
      - title: Геометрическая оптика
        steps: biotech-lection/3_em/70_optics.yaml
      - title: Волновая оптика
        steps: biotech-lection/3_em/80_optics.yaml
      - title: Квантовая оптика
        steps: biotech-lection/3_em/91_optics.md